### PR TITLE
Add Yoshi Tech OSD

### PR DESCRIPTION
**Pull request by Kounotori-ssbm**
added only "Jump OoParry" for now.

And, I thought Fighters with Fighter-specific Techniques is not only Spacies but also Yoshi and so on,
so I rename to OSD of "Spacie Tech" to "Fighter-specific Tech"

### CODE REVIEW

**Comment by AlexanderHarrison** [comment]
Great idea changing spacie tech to fighter-specific tech. Makes a lot of sense.

A few things:
1. It looks like the OSD is green when yoshi parries frame 5, and red otherwise. Is it optimal to jump frame 5, rather than frame 1?
2. The spacie tech and yoshi tech are injected into the same location (only an instruction apart), so they should be merged into a single injection.
3. Could you add some comments/documentation to the loads and saves? It's very nice to know what is being loaded/stored.

Looks great otherwise! :+1:

**Comment by Kounotori-ssbm** [comment]
> 1. It looks like the OSD is green when yoshi parries frame 5, and red otherwise. Is it optimal to jump frame 5, rather than frame 1?

"When is OPTIMAL Yoshi's parry-canceling frame" is a difficult issue.
Yoshi's parry is 6 frames long.
´´´
1. invincible
2. invincible [first cancelable frame]
3. invincible + shieldbox (head Invincibility is outside of shield)
4. invincible + shieldbox (slight head Invincibility is outside of shield)
5. invincible + shieldbox (almost Invincibility in shield)
6. invincible + shieldbox (almost Invincibility in shield) [last cancelable frame]
´´´
At least, 1 is not optimal because keeping Invincibility is too short.

It's impotant which is intended to parry against hitbox or grabbox because shieldbox is prior to Invincibility against hitbox and it makes powershield.

So,
Against hitbox, I think 2 of 3 is optimal because shieldbox makes powershield.
Against grabbox, 5 is optimal because it is longest Invincibility and shieldbox makes nothing against grabbox.

I focused on latter.



> 2. The spacie tech and yoshi tech are injected into the same location (only an instruction apart), so they should be merged into a single injection.

Do you mean all asm code of fighters' fighter-specific techs should be in one asm file?
I thought it's better one file is for one fighter.



> 3. Could you add some comments/documentation to the loads and saves? It's very nice to know what is being loaded/stored.

okay!

**Comment by Kounotori-ssbm** [comment]
I've integrated fighter-specific tech OSD code to 1 file!

**Comment by AlexanderHarrison** [comment]
Ok, if yoshi's parry doesn't have an optimal frame, then I think it makes sense to just have the text white rather than red and green. If it's possible, it would be cool to know how many frame late you jumped after being hit in parry, that would be useful.

**Comment by Kounotori-ssbm** [comment]
> Ok, if yoshi's parry doesn't have an optimal frame, then I think it makes sense to just have the text white rather than red and green.

I see, I have fixed to White text!


> If it's possible, it would be cool to know how many frame late you jumped after being hit in parry, that would be useful.

Sorry, it seems to be difficult for me for my skill now.

**Comment by AlexanderHarrison** [comment]
Perfect! Thank you!

**Pull request merged**
