### PR TITLE
Add percents for tech options

### PR DESCRIPTION
**Pull request by strabitz**
Let the player set the proportion of how the CPU will tech

### CODE REVIEW

**Comment by AlexanderHarrison** [comment]
Couple things:

- I think the percentages+tech option+getup option+invisibility should be folded into a "Tech Options" menu. When a user wants to set counter actions/tech invisibility and DI/SDI, they have to scroll through 8 more niche options every time. This will get old fast. And I think CPU Options is getting a bit cluttered.
- How the other percentages change when one is raised/lowered wasn't intuitive to me. But it seems possible to reach every percentage and I don't know a better way to do it, so I don't think it's a big deal.
- All the Lab_Change****Chance functions should be folded into a one function for tech options and one for getup options, if possible.

**Comment by strabitz** [comment]
>I think the percentages+tech option+getup option+invisibility should be folded into a "Tech Options" menu. When a user wants to set counter actions/tech invisibility and DI/SDI, they have to scroll through 8 more niche options every time. This will get old fast. And I think CPU Options is getting a bit cluttered.

Great idea. I also made a change to disable the random options if the getup/tech isn't set to random, so the cursor will skip over them.

>How the other percentages change when one is raised/lowered wasn't intuitive to me. But it seems possible to reach every percentage and I don't know a better way to do it, so I don't think it's a big deal.

Yep you're completely right. I made it a bit more coherent, basically any operation will now modify the next option. for example, if you add to tech in place, it will take away from tech away, then changing tech away will affect tech in, tech in will affect miss tech, and miss tech will affect tech in place. This way you can set your percents starting from the top

> All the Lab_Change****Chance functions should be folded into a one function for tech options and one for getup options, if possible.

This one is hard, since the Lab_Change****Chance functions are called when the option is changed, and it passes the value through. If we don't have a function for each option, then as far as I'm aware there would be no way to know what option is being changed when the function is being called. It's a lot of extra code but I think this is fine tbh

**Comment by AlexanderHarrison** [comment]
I've separated the functionality into a rebound_tech_chances function. lmk if you like this version or your better. Mine is definitely shorter, but yours is definitely simpler..

**Comment by strabitz** [comment]
@AlexanderHarrison I like yours a lot better. I think it would make more sense to move the tech and getup options to the separate tech options menu next to the chances though, but if you prefer them being back in the CPU options menu, make sure to also move the getup option back as well.

**Comment by strabitz** [comment]
Especially since there’s a bunch of players labbing out and requesting additional changes to tech chasing, I don’t think we should keep the tech options separate from the rest of the setting

**Comment by AlexanderHarrison** [comment]
I don't believe I changed the location of the tech chances, they should still be the same place as the other tech options. Can you send a screenshot or something? I did move the tech options into the CPU Options menu though.

**Comment by strabitz** [comment]
Screenshot_2024-09-28_at_10 50 38_AM
I think it should stay like this

**Comment by strabitz** [comment]
I’m out until tomorrow so I can’t check this right now

**Comment by AlexanderHarrison** [comment]
That's what it looks like on my end, so I'm mergin.

**Pull request merged**
