### PR TITLE
Resolve conflicts between MEX struct and ASM

### PR DESCRIPTION
**Pull request by NickCondron**
~~Draft PR until I can figure out if this fixes the "weird SDI" OSD bug. My theory is that writes to `iasa_frames` could have been modifying the memory the SDI OSDs try to use.~~

I realized the MEX/TM structs don't affect savestates, so I reworded the comment there. Fixed some other weirdness in the asm.

### CODE REVIEW

**Comment by NickCondron** [comment]
I also removed the dash out of laser stun asm. The old code used the wrong offsets. However, even after updating to the new offsets it still didn't work right (Could detect dash out of laser, but didn't give correct frame count). I decided to remove the asm because I can't be bothered to correct it and it had some inherent flaws.

**Comment by AlexanderHarrison** [comment]
What were the inherent flaws? I feel like we should try to fix this OSD. It's one of the more important ones imo.

**Comment by NickCondron** [comment]
1. It has a fixed position that would conflict with some of the work I thought you were doing on preventing OSDs from overlapping.
2. It only works for dash out of grounded stun, not other "act out of laser" actions.
3. Doesn't detect acting too early. If you dash too early and get a walk for example it won't display anything.
4. Doesn't account for crouch cancel against lasers
5. The OSD has a different visual style than the normal ones.
6. I thought it might be replaceable by a general act out of hitstun OSD

If you want to drop that commit and make an issue to fix it that's fine. I'm generally against fixing old ASM. We should be replacing broken functionality with C imo.

**Comment by AlexanderHarrison** [comment]
Agreed, a general act out of hitstun code should be possible.

**Pull request merged**
