### PR TITLE
Add additional SDI options and make SDI function properly

### PR DESCRIPTION
**Pull request by strabitz**
Add SDI in different cardinal directions, and also a "Very High" option that will trigger on every frame. Also fix SDI to do more than one SDI, it will now alternate between the cardinal and a region a bit out of the deadzone. We might want to adjust the random values for these.

### CODE REVIEW

**Comment by strabitz** [comment]
I'm going to make sure this is working the way I think it's supposed to

**Comment by strabitz** [comment]
this should be good now

**Comment by AlexanderHarrison** [comment]
Looks like away and towards SDI is broken.

**Comment by strabitz** [comment]
Got it, I'm gonna replace the calculation they're doing right now since it's a little too complicated given how SDI works

**Comment by strabitz** [comment]
@AlexanderHarrison I believe toward and away SDI are fixed

**Comment by AlexanderHarrison** [comment]
Looks like the CPU is always intangible to me.

**Comment by strabitz** [comment]
ah, lemme rebase onto the latest...

**Comment by strabitz** [comment]
@AlexanderHarrison check now

**Pull request merged**
