### PR TITLE
m-ex update header files

### PR DESCRIPTION
**Pull request by NickCondron**
This was a lot of work. Backwards compatibility of savestates means there is some ugliness in some parts of the code, but I left comments in those places.

### CODE REVIEW

**Comment by AlexanderHarrison** [comment]
Looks like the anim frame is always reset to 1 after load state. Looked into it a bit, looks like the correct value is being loaded, but then being reset somehow.

**Comment by NickCondron** [comment]
> Looks like the anim frame is always reset to 1 after load state. Looked into it a bit, looks like the correct value is being loaded, but then being reset somehow.

The game thinks the character is dying off the left side of the stage. Investigating.

**Comment by NickCondron** [comment]
memset and memcpy were commented out in useful.h

Shocked the code compiled or worked at all without this. We need to work on enabling errors/warnings for things like that. This fixes the issue of fox dying on the ICs savestate before the `Fighter_UpdateShieldGFX()` call was added. However, without the line I get nondeterministic input from the CPU. Sometimes popo does different throws.

**Comment by AlexanderHarrison** [comment]
Still running into the same issue where the animation frame is being reset to 1 on restore. Using latest dolphin build.

Replicate:
- Enter the lab as marth
- pause in the middle of fair
- save then immediately restore state
- marth is now at beginning of fair animation

Also just found that models can be glitchy, restore on dreamland and the stage will occasionally flash black.

**Pull request merged**
